import img1 from '../../assets/images/past-projects/p-1.png';

export const products = [
  {
    sale: 'For Sale',
    title: '4321 Alton Rd, Miami, Beach',
    location: 'Miami Beach',
    image: img1,
    squareTitle: '2923 Square Footage',
    bedTitle: '3 Bedrooms',
    garageTitle: '2 Garages',
    bedRoomTitle: '3 Bathrooms',
    amount: 'Loan Amount: $328,000',
    rate: 'Rate: 11.75%',
    ltv: 'LTV: 84.65%',
    term: 'Term: 12 Months',
    price: '$3,45,000',
  },
  {
    sale: 'For Sale',
    title: '4321 Alton Rd, Miami, Beach',
    location: 'Miami Beach',
    image: img1,
    squareTitle: '2923 Square Footage',
    bedTitle: '3 Bedrooms',
    garageTitle: '2 Garages',
    bedRoomTitle: '3 Bathrooms',
    amount: 'Loan Amount: $328,000',
    rate: 'Rate: 11.75%',
    ltv: 'LTV: 84.65%',
    term: 'Term: 12 Months',
    price: '$3,45,000',
  },
  {
    sale: 'For Sale',
    title: '4321 Alton Rd, Miami, Beach',
    location: 'Miami Beach',
    image: img1,
    squareTitle: '2923 Square Footage',
    bedTitle: '3 Bedrooms',
    garageTitle: '2 Garages',
    bedRoomTitle: '3 Bathrooms',
    amount: 'Loan Amount: $328,000',
    rate: 'Rate: 11.75%',
    ltv: 'LTV: 84.65%',
    term: 'Term: 12 Months',
    price: '$3,45,000',
  },
];
