export const footerInfo = [
  {
    heading: 'Company',
    link1: 'About',
    link2: 'Fix And Flip Loans',
    link3: 'DSCR Rental Loans',
    link4: 'Ground Up Construction Loans',
    link5: 'Where We Lend',
    link6: 'Florida',
    link7: 'Texas',
    link8: 'Georgia  ',
  },
  {
    heading: 'Top Cites We Lend In',
    link1: 'Orlando',
    link2: 'Tampa',
    link3: 'Miami',
    link4: 'Jacksonville',
    link5: 'Austin',
    link6: 'Dallas',
    link7: 'San Antonio  ',
  },
  {
    heading: 'Top Resources',
    link1: 'Loan Calculator',
    link2: 'What is a Hard Money Loan',
    link3: 'What is a Hard Money Loan',
    link4: 'How to find fix and flip deals',
    link5: 'Best Cities for Fix and Flips',
    link6: 'Useful Link',
    link7: 'Privacy Policy',
    link8: 'Terms of Use  ',
  },
];
